FROM tleemcjr/metasploitable2

USER root

RUN mkdir -p /home/msfadmin/Desktop \
             /home/msfadmin/Documents \
             /home/msfadmin/Downloads \
             /home/msfadmin/Tools && \
    chown -R msfadmin:msfadmin /home/msfadmin

COPY motd.meta /etc/motd
RUN sed -i 's/\r//' /etc/motd

COPY bashrc.meta /home/msfadmin/.bashrc
RUN sed -i 's/\r//' /home/msfadmin/.bashrc && \
    chown msfadmin:msfadmin /home/msfadmin/.bashrc

CMD ["/bin/bash", "-c", "/etc/init.d/ssh start 2>/dev/null; /etc/init.d/xinetd start 2>/dev/null; /etc/init.d/openbsd-inetd start 2>/dev/null; /etc/init.d/apache2 start 2>/dev/null; /etc/init.d/mysql start 2>/dev/null; exec /bin/bash"]
